#
# kmux example tmux.conf
#
# Source this file from an absolute path, for example:
#   tmux -f /path/to/kmux/example_tmux.conf
#

# Enable RGB colour if running in xterm(1)-like terminals.
set-option -sa terminal-features ",xterm*:RGB"

# Use tmux-256color by default.
set -g default-terminal "tmux-256color"

# Load kmux example theme and keybindings relative to this file.
source-file -F "#{d:current_file}/themes/kmux-base.conf"
source-file -F "#{d:current_file}/keybindings/kmux-keys.conf"
